### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [mark0smith/Maltego_with_Fofa#1]
hi I've problem
Traceback (most recent call last):
  File "Fofa_Query_subdomains_with_Domain.py", line 1, in <module>
    from maltego_trx.entities import Domain,Website,URL
ModuleNotFoundError: No module named 'maltego_trx'

can you help?

**Comment by mark0smith** [comment]
不是很懂，你有更多的信息吗？比如如何复现和对应的截图等。
